apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kustomization02
  namespace: flux-system
spec:
  url: https://github.com/ondrejsika/fluxcd-training.git
  timeout: 60s
  interval: 1m0s
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustomization02
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: kustomization02
  path: ./examples/kustomization02_hello_world/
  interval: 1m0s
  prune: true
  force: false
